name: Trigger E2E tests on push
on:
  push:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: DevExpress/testcafe-action@latest
        with:
          args: chrome --test-meta category=sanity
