name: Trigger E2E tests on push
on:
  push:
    branches: [main]

jobs:
  e2e-tests-on-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build . -t e2e:v1
      - run: docker run -e BROWSER=chrome -e CATEGORY=sanity e2e:v1